### ISSUE TITLE
Wrong format in documented cronjob_time

### ISSUE THREAD

**Issue by llauren** [gerardkok/puppet-reposado#5]
`README.md` says that the format for `cronjob_time` should be `'[HH, MM]'` but the code says the format is `'HH:MM'`. I trust the code :)

**Comment by gerardkok** [comment]
Thanks for spotting this; I've fixed the README, and also changed the data type of `cronjob_time`, so incorrectly formatted values should now result in an error.

I'll release after solving (trying to solve...) [#6](/gerardkok/puppet-reposado/issues/6).
