### ISSUE TITLE
cronjob_command should honour configured base_dir

### ISSUE THREAD

**Issue by llauren** [gerardkok/puppet-reposado#6]
`$cronjob_command` defaults to the values from `reposado::params`, even if the user changes `$base_dir`. This will cause the cron job to fail if i change the `reposado:base_dir` but don't specify the `cronjob_command`. 

A more obvious solution for the user would for the `cronjob_command` to be derived using the effective `$base_dir` in https://github.com/gerardkok/puppet-reposado/blob/4291cc5f37cd39e5e926a3bc7c9c99af5c5dd2a7/manifests/init.pp#L66 if it hasn't been explicitly set.

Or in other words, if i change the `$base_dir`, the `cronjob_command` should be updated accordingly, by evaluating it using `$base_dir` and not the `reposado::params`.

Does that make any sense to you?

**Comment by gerardkok** [comment]
I've tried to fix this with release 1.0.1. Please let me know if it doesn't work.
