### ISSUE TITLE
Puppet functions have not been updated for 10.14

### ISSUE THREAD

**Issue by robert4man** [gerardkok/puppet-reposado#9]
The catalog url and rewrite fall into the else 10.13 and get duplicated.

**Comment by robert4man** [comment]
It looks like what I need is in the Mojave branch. I haven't tested it yet, but it looks like a significant improvement. Is there any reason it hasn't made it into master and been published to Puppet Forge? Do you need assistance finishing it up?

**Comment by robert4man** [comment]
I tested the Mojave branch with our environment and it seems to work perfectly. I can also verify it works on RHEL/CentOS7.

**Comment by gerardkok** [comment]
Thanks for the heads up! I totally forgot about it. I've merged now, and published the new version on the forge.

I'm a bit pressed for time, so I'll look into supporting RHEL/Centos later, but it's good to hear it works. I also haven't had time to look into the ordering of AppleCatalogURLs (apparently you need to list 10.14 before 10.13, but the module currently does not enforce that. See also https://groups.google.com/forum/?fromgroups#!topic/reposado/qUZBN0Ow8J4).

**Comment by robert4man** [comment]
Thanks for the update, and thanks for the heads up on the 10.13/10.14 ordering issue. I will research that issue and open an issue ticket if appropriate. I may have a student worker I can have work on a code fix and submit a PR.

**Comment by robert4man** [comment]
FYI: according to the MacAdmins Slack channel, it looks like the 10.13/10.14 ordering issue has been resolved upstream by Apple.
